### ISSUE TITLE
[DOCS]: Node.js version must be 20 when using the latest octokit/action.

### ISSUE THREAD

**Issue by TomohiroAkutsu** [octokit/action.js#565]
### Describe the need

I want you to write the version of Node.js in the README.md. For example, the following.

<table>
<tbody valign=top align=left>
<tr><th>
Browsers
</th><td width=100%>

`@octokit/action` is not meant for browser usage.

</td></tr>
<tr><th>
Node
</th><td>

Install with `npm install @octokit/action`

```js
const { Octokit } = require("@octokit/action");
// or: import { Octokit } from "@octokit/action";
```

</td></tr>

<tr><th>
Node.js version
</th><td width=100%>

20

</td></tr>
</tbody>
</table>

I encountered the following error in my environment when running the latest octokit/action (v6.0.7) on Node.js 16.
~~~
/home/runner/work/path-to-directory/node_modules/@octokit/action/node_modules/undici/lib/fetch/response.js:506
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
at Object.<anonymous> (/home/runner/work/path-to-directory/node_modules/@octokit/action/node_modules/undici/lib/fetch/response.js:506:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/runner/work/path-to-directory/node_modules/@octokit/action/node_modules/undici/index.js:118:27)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
~~~
This error no longer occurs after updating Node.js to 20.
Or even with Node.js 16, the error can be avoided by specifying the version like `npm install @octokit/action@6.0.6` .

### SDK Version

octokit/actions v6.0.7

### Relevant log output

```shell
/home/runner/work/path-to-directory/node_modules/@octokit/action/node_modules/undici/lib/fetch/response.js:506
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
at Object.<anonymous> (/home/runner/work/path-to-directory/node_modules/@octokit/action/node_modules/undici/lib/fetch/response.js:506:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/runner/work/path-to-directory/node_modules/@octokit/action/node_modules/undici/index.js:118:27)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
It's documented in the `package.json`:
https://github.com/octokit/action.js/blob/main/package.json#L101

You shouldn't have been able to install it from NPM without seeing any kind of error

**Comment by wolfy1339** [comment]
The V6 releases dropped support for NodeJS v14&16

https://github.com/octokit/action.js/releases/tag/v6.0.0

**Comment by TomohiroAkutsu** [comment]
Oh, I had overlooked that. Thank you.
